<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Omni.ServiceRegistry.Services\Omni.ServiceRegistry.Services.csproj" />
    <ProjectReference Include="..\Omni.ServiceRegistry.Data\Omni.ServiceRegistry.Data.csproj" />
    <ProjectReference Include="..\Omni.ServiceRegistry.Models\Omni.ServiceRegistry.Models.csproj" />
    <ProjectReference Include="..\Omni.ServiceRegistry.Interfaces\Omni.ServiceRegistry.Interfaces.csproj" />
  </ItemGroup>

</Project>
