
﻿// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Omni.ServiceRegistry.Data.Postgres;

#nullable disable

namespace Omni.ServiceRegistry.Data.Postgres.Migrations
{
    [DbContext(typeof(ServiceRegistryDbContext))]
    [Migration("20251116000154_AddServiceDeletionFields")]
    partial class AddServiceDeletionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Omni.ServiceRegistry.Models.RegistrationRequest", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HeartbeatTimeout")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMissedHeartbeats")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ServiceNameNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegistrationId");

                    b.HasIndex("ServiceNameNormalized")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("Status");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("Omni.ServiceRegistry.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletionApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletionComments")
                        .HasColumnType("text");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionRequestedBy")
                        .HasColumnType("text");

                    b.Property<int>("DeletionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("integer");

                    b.Property<long>("HeartbeatCount")
                        .HasColumnType("bigint");

                    b.Property<int>("HeartbeatTimeout")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastHeartbeatTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxMissedHeartbeats")
                        .HasColumnType("integer");

                    b.Property<int>("MissedHeartbeatCounter")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ServiceNameNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceId");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("HealthStatus");

                    b.HasIndex("LastHeartbeatTimestamp");

                    b.HasIndex("ServiceNameNormalized")
                        .IsUnique()
                        .HasFilter("\"DeletionStatus\" != 2");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Omni.ServiceRegistry.Models.ServiceChangeHistory", b =>
                {
                    b.Property<Guid>("ChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("ChangeId");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceChangeHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
